### ISSUE TITLE
Add a few sentences to describe each section 

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/Token-Log-Hatch-Params#72]
From @Jeff-Emmett

**Comment by Jeff-Emmett** [comment]
Suggested content:
=========================
![image.png](https://images.zenhubusercontent.com/5cae1c1852320c5dff5b4586/d37eb9de-ce69-4aad-b34d-b76f04eccd9e)


<Top of Page>
**TEC Hatch Dashboard**
This dashboard is a tool to collect community opinions on the proper parameterization of the Token Engineering Commons.  There are three sections of the dashboard, where you can parameterize three different segments of the initial TEC ecosystem. At the end of the dashboard, you can choose to submit your parameterization configuration to the TEC Github, where it auto-compile into a report that can be compared and contrasted among other parameterization submissions by the community.  This tool is meant to inform the community about the decisions that go into launching the TEC (and other Commons), and foster discourse in the ethical design of community ecosystems.  Click "Import params" below to begin!

<Import Params>

**Section 1: Choosing Parameters for Impact Hours - Rewarding TEC Contributions**
This section of the dashboard will look at the parameters involved in valuing Impact Hours, which have been awarded to active contributors of the TEC since mid-2020. A portion of funds raised in the TEC Hatch will go to pay off the accumulated Impact Hours debt for work already completed - your task is to choose the parameters that strike a fair balance between past and future contributions. 

![image.png](https://images.zenhubusercontent.com/5cae1c1852320c5dff5b4586/dcf2f71b-7e70-42bd-b88a-70d820e2f545)

**Section 2: Choosing Parameters for the TEC Hatch DAO**
This section of the dashboard will look at the parameters involved in Hatching the Dandelion DAO for the TEC. These parameters include configuring the max and min of the raise, the length of the Hatch, the exchange rate of the token, and the maximum TEC tokens available per CSTK score.

![image.png](https://images.zenhubusercontent.com/5cae1c1852320c5dff5b4586/9f10b0b8-708f-48b9-ad24-e2e55a52ea1f)

**Section 3: Dandelion Voting - Dandelion DAO Initialization**
Dandelion DAOs are essentially Moloch++, deployed on the Aragon framework. This section of the dashboard will look at the parameters involved in Dandelion Voting, such as required quorum and support for votes to pass, vote duration, buffer periods, and rage quit window.

**Comment by GriffGreen** [comment]
@mendesfabio 

Hatch

The Hatch is the initialize phase that collects wxDai and mints TECH tokens for the TEC Hatch DAO, see the [Hatch TL;DR](https://forum.tecommons.org/t/the-hatch-tl-dr/272) for a general overview. Designing the Hatch includes a few important concepts like: the Impact Hours Slope and Maximum Impact Hour Rate, which will award TECH tokens to the Impact Hour token holders via the Cultural Build Tribute; the Membership Ratio that determines how the CSTK Score influences how much wxDai each member of the Trusted Seed can send to the Hatch; the Hatch Tribute that sets wxDai aside for advancing Token Engineering and choosing the Minimum, Maximum Goals as well as specifying your Target Goal that you are designing around. For a more complete understanding of each Parameter, see the [Hatch Spec](https://forum.tecommons.org/t/tec-test-hatch-implementation-specification/226)


TEC Hatch DAO

The TEC Hatch DAO is effectively a Moloch DAO deployed using the Aragon framework. Designing how the DAO will make decisions is pretty straight forward, the variables that may need a special note are: Minimum Quorum which only counts yes votes; Vote Proposal Buffer, which is a precautionary variable that ensures DAO members have time between votes to Rage Quit and the Rage Quit Period which is the time after a vote that a DAO member has to exit with their share of the Redeemable Pool before the vote is executed. For a more complete understanding of each Parameter, see the [Hatch Spec](https://forum.tecommons.org/t/tec-test-hatch-implementation-specification/226)

**Comment by freedumbs00** [comment]
This has been resolved and closing the issue
